### ISSUE TITLE
Phone numbers

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#68]
Two things:
-what if someone doesn't have a phone number?  Is there a risk in putting the RMH number in as a default?
-is the current system set up that it can accept numbers from out side the US?  Just ran across someone from the UK.

**Comment by megandalster** [comment]
Everyone needs a phone number so that their entry in the database is unique.  If you assign the RMH number to a person or more, that's okay as long as all those persons have different first names.  (So it's okay to do this, but be careful not to assign the RMH number to two persons named Brittney, for example.  If you do this by mistake, the system will lose one of them.)

As for international phone numbers, the only Homeroom requirement is that the number be 10 digits long.  Since UK phone numbers are 9 or 10 digits, you can use them by adding a prefix 0 at the beginning of a 9-digit number.  You should also add a note for the guest that their phone is a UK number and should be prefixed by +44 for calling from the US.
