### ISSUE TITLE
Editing guest

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#69]
I had a guest (Brittany Garland) whose address changed.  I edited her profile and saved it.  Now when I search for her, she comes up twice (once with the old address and once with the new one).  All of her prior bookings show under both profiles.  I'm assuming we want to avoid duplicates?

**Comment by gnoonan** [comment]
Just had another.  Searched for Kunn:
![image](https://cloud.githubusercontent.com/assets/14204120/12210589/10c7343c-b629-11e5-9cd5-16696b6df729.png)

Edited the profile, saved it then searched again and now there twice:
![image](https://cloud.githubusercontent.com/assets/14204120/12210620/42d944ba-b629-11e5-8a0c-477ccb63698c.png)

**Comment by megandalster** [comment]
In this case, Brittney is in the database twice because she has two different phone numbers, one ending in 3077 and the other ending in 4909.  (Remember that the first name and primary phone identifies each person's unique id in the database, so the system thinks there are two different Brittney's, one for each phone number.)

So to fix this one, just delete the record that has an incorrect phone number for Brittney (and keep the other).
